version: '3.8'

# Virginia Land Grants LLM Geolocation
# 
# Data Organization:
# - Public data included: data/raw/limited_excerpts_45_abstracts.csv, data/raw/metadata_with_hashes.csv, data/processed/validation.csv
# - Private data excluded: data/raw/raw_cavaliers_extract.csv (mount separately if available)
# - See data/COPYRIGHT_COMPLIANCE.md for full details

services:
  geolocation:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    volumes:
      - ./results:/app/results
      - ./data:/app/data
      - ./config:/app/config
    working_dir: /app
    command: python3 code/run_experiment.py --evalset data/processed/validation.csv 